app_service_name      = "prancer-app-service"
app_service_plan_name = "prancer-app-plan"
sql_endpoint          = "prancer-sql-endpoint"
sql_connection        = "prancer-sql-connection"
keyvault_endpoint     = "prancer-kv-endpoint"
keyvault_connection   = "prancer-kv-connection"
resource_group        = "prancer-app-rg"
location              = "eastus2"
