variable "app_service_name" {}
variable "app_service_identity_type" {}
variable "app_service_plan_name" {}
variable "app_service_plan_kind" {}
variable "app_service_plan_tier" {}
variable "app_service_plan_size" {}
variable "app_service_plan_capacity" {}
variable "sql_endpoint" {}
variable "keyvault_endpoint" {}
variable "resource_group" {}
variable "location" {}
variable "tags" {}
